### ISSUE TITLE
Why does it suck?

### ISSUE THREAD

**Issue by joelworsham** [Dynamictivity/dyson#1]
Your readme says that it sucks... why?

https://i.imgur.com/pXC4wCW.png

**Comment by Pharserror** [comment]
It's a vacuum joke

**Comment by Theaxiom** [comment]
Yes and no: https://en.wikipedia.org/wiki/Dyson_sphere

Thanks,
Travis Rowland
http://travisrowland.com
http://linkedin.com/in/travisrowland
http://about.me/travisrowland

---

This e-mail is privileged and confidential.  Do not forward, copy or print
without authorization.  If you are not the intended recipient of this
E-mail, you are hereby notified that any dissemination, distribution or
copying of this message is strictly prohibited. If misdirected, please
delete and notify the sender by e-mail at travis.rowland@gmail.com.

CAUTION: E-mail sent through the internet is not secure and could be
intercepted by a third party. For your protection, avoid sending
identifying information, such as account numbers or social security numbers.

**Comment by ddavison** [comment]
because you hijacked my readme and tainted it with your sucky subtitle.  pun intended.

**Comment by joelworsham** [comment]
Whaaaaa? Me? I would never...

**Comment by joelworsham** [comment]
8 commits in... going strong

**Comment by joelworsham** [comment]
WHAT HAVE YOU DONE
